# Zdaje sobie sprawę, iż user/password i db jako raw data jest nielegalne, natomiast w celu ułatwienia logistycznego włączenia tego dockera, nie używam zmiennych środowiskowych
version: '3.8'

services:
  app:
    build:
      context: ../test-backend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - PORT=8081
    depends_on:
      - db 

  db:
    image: postgres:14.1-alpine
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database
    # Używam ports zamiast expose w celu ewentualnej możliwości postawienia bazy danych na publicznym porcie localhost:docker zamiast prywatnym dla sieci dockerowej (expose).
    ports:
      - "5432:5432"